services:
  commtracker-api:
    container_name: commtracker-api
    restart: always
    build: .
    #ports:
    #  - "3004:3004"
    volumes:
      - .:/app
      - /app/node_modules
      - node-tls:/node-tls
    networks:
      - prod-network

volumes:
  node-tls:
    external: true
    name: node-tls

networks:
  prod-network:
    external: true
    name: prod-network
